# Generated by Django 5.0 on 2024-09-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='Event.Participation', to='Person.person'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('person', 'event')},
        ),
    ]
