# Generated by Django 5.0 on 2024-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cin', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('events', models.ManyToManyField(through='Event.Participation', to='Event.event')),
            ],
        ),
    ]
